Repository janus-idp/showcase-e2e, pull requests merged in 2023-10, with the labels that each got.

#41 PR test is broken
  .ibm/pipelines/auth/secrets-rhdh-secrets.yaml
  .ibm/pipelines/auth/service-account-rhdh-secret.yaml
  .ibm/pipelines/openshift-tests.sh
  .ibm/pipelines/resources/cluster_role/cluster-role-k8s.yaml
  .ibm/pipelines/resources/cluster_role/cluster-role-ocm.yaml
  .ibm/pipelines/resources/cluster_role_binding/cluster-role-binding-k8s.yaml
  .ibm/pipelines/resources/cluster_role_binding/cluster-role-binding-ocm.yaml
  .ibm/pipelines/resources/config_map/configmap-app-config-rhdh.yaml
  .ibm/pipelines/resources/deployment/deployment-test-app-component.yaml
  .ibm/pipelines/resources/service_account/service-account-rhdh.yaml
  .ibm/pipelines/value_files/values_showcase.yaml
  README.md
Labels: approved

#44 chore(workflow): add add-to-project workflow
  .github/workflows/add-to-project.yaml
Labels: lgtm

#40 cypress setup and guest Sign in e2e test case
  e2e-test/cypress.config.ts
  e2e-test/cypress/e2e/backstage_home.spec.ts
  e2e-test/cypress/e2e/guest-signin-happy-path.spec.ts
  e2e-test/cypress/support/e2e.ts
  e2e-test/cypress/support/index.d.ts
  e2e-test/cypress/support/pageObjects/global-obj.ts
  e2e-test/cypress/support/pageObjects/page-obj.ts
  e2e-test/cypress/support/pages/HomePage.ts
  e2e-test/cypress/support/testData/gpts.ts
  e2e-test/cypress/utils/Common.ts
  e2e-test/cypress/utils/UIhelper.ts
  e2e-test/package.json
  e2e-test/yarn.lock
Labels: lgtm, approved

#49 GitHub Sign-in and Catalog Test automation
  e2e-test/cypress/e2e/github-happy-path.spec.ts
  e2e-test/cypress/support/e2e.ts
  e2e-test/cypress/support/hooks.ts
  e2e-test/cypress/support/pageObjects/page-obj.ts
  e2e-test/cypress/support/pages/CatalogImport.ts
  e2e-test/cypress/utils/Common.ts
  e2e-test/cypress/utils/UIhelper.ts
  e2e-test/package.json
  e2e-test/yarn.lock
Labels: lgtm, approved

#52 [RHIDP-484] Create ibmcloudtest image
  .ibm/images/Dockerfile
  .ibm/images/README
Labels: lgtm, approved
